events {
    worker_connections 1024;
}

http {
    upstream auth_backend {
        server auth-service:8000;
    }

    upstream repo_backend {
        server repo-service:8000;
    }

    upstream git_backend {
        server git-service:8000;
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://auth_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/repositories {
            proxy_pass http://repo_backend/repositories;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/repos/ {
            proxy_pass http://git_backend/repos/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            access_log off;
            return 200 '{"status":"gateway healthy"}';
            add_header Content-Type application/json;
        }
    }
}